custom_admin_config.settings_form:
  path: '/admin/config/custom/settings'
  defaults:
    _form: '\Drupal\custom_admin_config\Form\SettingsForm'
    _title: 'Custom Settings Form'
  requirements:
    _permission: 'access administration pages'
  options:
    _admin_route: TRUE