 custom_admin_config.settings_form:
  title: 'SettingsForm'
  route_name: custom_admin_config.settings_form
  description: 'A description for the menu entry'
  parent: system.admin_config_system
  weight: 99